### ISSUE TITLE
themes, to be edited

### ISSUE THREAD

**Issue by Gertone** [MarkupUK/MarkupUK#1]
We welcome contributions and discussions along the following themes

·  Managing metadata solutions in publishing projects;
·  Project experiences that merge the XML solution stack with linked data
·  Topic based single sourcing stories, stories including but restricting to DITA
·  Practical use of XML in digital humanities and education

Although we do encourage contributions within the above themes, we do of course welcome more general markup related contributions

**Comment by sgmlguru** [comment]
I like the list. Some copy editing:

·  Managing metadata in publishing;
·  Merging the XML solution stack with linked data
·  Topic-based single-source stories including but not restricted to DITA
·  Practical use of XML in digital humanities and education

Although we encourage contributions within the above themes, we also welcome other markup-related contributions.

**Comment by yamahito** [comment]
I think we could cut down the language even further...  maybe combining digital humanities and publishing?

I think that it would be good to namedrop technologies for people searching for DITA, TEI, etc - but maybe that should be in some separate text?  A word-cloud, perhaps?
-------

We welcome quality contributions on any markup related theme, particularly those regarding:
- Markup in digital humanities, publishing, or education
  - User Stories
  - Challenges
  - Topic based publishing
  - Single Source publishing
- Managing metadata in publishing
- Trees and Graphs: conflicts, overlap, and sweet spots

**Comment by Gertone** [comment]
Sounds good. In my point of view you can put that on the website

**Comment by sgmlguru** [comment]
Yes, fine by me.

**Comment by AndrewSales** [comment]
Agree.
