### ISSUE TITLE
Please archive Markup UK 2021 papers

### ISSUE THREAD

**Issue by AndrewSales** [MarkupUK/MarkupUK#24]
From @tgraham-antenna:
"Because the Markup UK 2021 papers are still in undated URLs (e.g.
https://markupuk.org/webhelp/index.html#ar02.html), it's currently not
possible to make a link to a 2021 paper that will still work after
Markup UK 2022.

Please move (or also make available) the Markup UK 2021 papers (HTML and
PDF) under more permanent URLs."

**Comment by AndrewSales** [comment]
Believe fixed, so closing.

**Comment by tgraham-antenna** [comment]
Now getting links like 'Previous conferences > 2023' pointing to https://markupuk.org/2023/2023/index.html

**Comment by tgraham-antenna** [comment]
Didn't pay attention to the date of your commit. The 'https://markupuk.org/2023/2023/index.html', etc., may be a separate problem, as 2023 postdates your commit.

**Comment by tgraham-antenna** [comment]
Thanks. Had only noticed it this week.
